aA-projects/w10D4/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'posts/create'
  get 'posts/update'
  get 'posts/destroy'
  get 'posts/edit'
  get 'posts/show'
  resources :subs 
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aA-projects/w10D4/reddit_clone/app/models/post.rb
class Post < ApplicationRecord
end

aA-projects/w10D4/reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, presence: true

    belongs_to :moderator,
    primary_key: :id, 
    foreign_key: :user_id,
    class_name: :User

    has_many :posts
end

aA-projects/w10D4/reddit_clone/app/models/user.rb
class User < ApplicationRecord
    validates :username, :password_digest, :session_token, presence: true 
    validates :username, uniqueness: true 
    validates :password, length: { minimum: 6, allow_nil: true }
    after_initialize :ensure_session_token

    attr_reader :password 
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64 
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return user if user && user.is_password?(password)
        nil
    end

    def generate_session_token!
        SecureRandom.urlsafe_base64(16)
    end

    def is_password?(password)
        bcrypt_password = BCrypt::Password.new(self.password_digest)
        bcrypt_password.is_password?(password)
    end

    def reset_session_token! 
        self.update!(session_token: generate_session_token!)
        self.session_token
    end
end

aA-projects/w10D4/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :logged_in?
    helper_method :current_user 

    def sign_in(user)
        @current_user = user
        session[:session_token] = user.reset_session_token!
    end 

    def sign_out
        current_user.reset_session_token!
        session[:session_token] = nil
    end

    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end    
    
    def logged_in?
        !!current_user
    end

    def require_signin
        redirect_to new_session_url unless logged_in?
    end

end

aA-projects/w10D4/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def show
  end
end

aA-projects/w10D4/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # @user = User.new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user
      sign_in(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username / password"]
      render :new
    end 
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

aA-projects/w10D4/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_signin
    
    def index
        @subs = Sub.all 
        render :index 
    end

    def new 
        @subs = Sub.new 
        render :new 
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.user_id = current_user.id 

        if @sub.save 
            redirect_to sub_url(@sub.id)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new 
        end
        
    end

    def show
        @sub = Sub.find(params[:id])
        render :show 
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit 
    end

    def update
        @sub = Sub.find(params[:id])

        if @sub.update(sub_params)
            redirect_to sub_url(@sub.id)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit 
        end
    end

    def destroy
        @sub = Sub.find(params[:id])
        @sub.destroy
        redirect_to subs_url
    end

    private
    def sub_params 
        params.require(:sub).permit(:title, :description)
    end

end

aA-projects/w10D4/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new 
    render :new 
  end

  def create
    @user = User.new(user_params)
    debugger
    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new 
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

aA-projects/w10D4/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        <<-HTML.html_safe
            <input type="hidden" 
            name="authenticity_token"
            value="#{form_authenticity_token}" >
        HTML
    end
end

aA-projects/w10D4/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

aA-projects/w10D4/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

aA-projects/w10D4/reddit_clone/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

aA-projects/w10D4/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
    
      <form action="<%= session_url %>" method="post">
        <%= auth_token %>
        <%= current_user.username %>
        <br>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign out!">
      </form>
      
    <% else %>

      <%= link_to 'Sign in!', new_session_path %>
      <%= link_to 'Sign up!', new_user_path %>

    <% end %>


    <%= yield %>
    <%= render 'layouts/errors' %>
  </body>
</html>

aA-projects/w10D4/reddit_clone/app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="post">
    <%= auth_token %>

    <label>
        Username
        <input type="text" name="user[username]">
    </label>

    <label>
        Password
        <input type="password" name="user[password]">
    </label>

    <input type="submit" value="Submit">

</form>